/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import codes.DBConnect;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author DELL
 */
public class MyOrders extends javax.swing.JFrame {

    /**
     * Creates new form MyOrders
     */
    Connection conn=null;
    PreparedStatement pst=null;
    String jComboSelectdValue="";
    String [] jComboArray={};
    double totalPrice=250;
    public MyOrders() {
        conn=DBConnect.connect();
        setDropDownMenu();
        initComponents();
        fetchDataFromDatabase();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        orderNowButtonHeader1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dropDown = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dynamicPanel = new javax.swing.JPanel();
        recursivePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        recursiveSeperator = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mainTotalPrice = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText(Login.userNameDisplay);
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 210, 40));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        jLabel2.setText("FOODIE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 110, -1));

        jButton1.setText("About Us");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 70, -1));

        jButton3.setText("Order Now");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, -1));

        orderNowButtonHeader1.setText("Home");
        orderNowButtonHeader1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        orderNowButtonHeader1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNowButtonHeader1ActionPerformed(evt);
            }
        });
        jPanel1.add(orderNowButtonHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1010, 1));

        dropDown.setModel(new javax.swing.DefaultComboBoxModel<>(jComboArray));
        dropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownActionPerformed(evt);
            }
        });
        jPanel1.add(dropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 940, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Show:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, 20));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        dynamicPanel.setBackground(new java.awt.Color(255, 255, 255));
        dynamicPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dynamicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recursivePanel.setBackground(new java.awt.Color(247, 247, 247));
        recursivePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        recursivePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Order");
        recursivePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("1");
        recursivePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 20, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Placed on:");
        recursivePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("2024/03/26");
        recursivePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 70, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderMenuImages/OIP (2).jpeg"))); // NOI18N
        recursivePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 120));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel14.setText("5000");
        recursivePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 110, 60));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Rs: ");
        recursivePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 30, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel17.setText("10");
        recursivePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 95, 30, 30));
        recursivePanel.add(recursiveSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 860, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel19.setText("Submarine");
        recursivePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 200, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("pcs");
        recursivePanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 40, 40));

        dynamicPanel.add(recursivePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 860, 240));

        jScrollPane1.setViewportView(dynamicPanel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 940, 520));

        mainTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(mainTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 80, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("My Orders");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Rs.");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public JPanel createpanel(String productName, int quantity, Date orderDate,int position,Double price, int orderNumber){

        
        recursivePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        recursiveSeperator = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();


        recursivePanel.setBackground(new java.awt.Color(247, 247, 247));
        recursivePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        recursivePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Order");
        recursivePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText(Integer.toString(orderNumber));
        recursivePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 20, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Placed on:");
        recursivePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText(orderDate.toString());
        recursivePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 70, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/displayImagesWithNames/"+productName+".jpeg"))); // NOI18N
        recursivePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 120));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel14.setText(Double.toString(price));
        recursivePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 110, 60));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Rs: ");
        recursivePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 30, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel17.setText(Integer.toString(quantity));
        recursivePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 95, 30, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("pcs");
        recursivePanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 40, 40));
        recursivePanel.add(recursiveSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 930, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel19.setText(productName);
        recursivePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 200, 40));

        dynamicPanel.add(recursivePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, position, 860, 240));
        
        

        return recursivePanel;
    }
    public void fetchDataFromDatabase(){
        try{
            conn=DBConnect.connect();
            String query = "SELECT productName, quantity, price ,date FROM userproducts where userName='"+Login.userNameDisplay+"' and date='"+jComboSelectdValue+"'";
            Statement statement=conn.createStatement();
            ResultSet resultSet=statement.executeQuery(query);
            
            int yPosition=30;
            int orderNumber=1;
            totalPrice=0;
            
            
            dynamicPanel = new javax.swing.JPanel();
            
            
            jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

            dynamicPanel.setBackground(new java.awt.Color(255, 255, 255));
            dynamicPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            dynamicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            
            jScrollPane1.setViewportView(dynamicPanel);

            
            
            while (resultSet.next()){
                String productName=resultSet.getString("productName");
                int quantity=resultSet.getInt("quantity");
                Date orderDate=resultSet.getDate("date");
                Double price=resultSet.getDouble("price");
                
                JPanel panel=createpanel(productName, quantity, orderDate,yPosition,price*quantity,orderNumber);
                yPosition+=270;
                orderNumber+=1;
                totalPrice+=price*quantity;
            }
            mainTotalPrice.setText(Double.toString(totalPrice));
            recursivePanel = new javax.swing.JPanel();
            recursivePanel.setBackground(new java.awt.Color(255, 255, 255));
            recursivePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
            recursivePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            
            dynamicPanel.add(recursivePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, yPosition-245, 860, 240));
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
        }
    }
    public void setDropDownMenu(){
        try{
            // Query to retrieve data
            String query = "SELECT distinct date FROM userproducts where userName='"+Login.userNameDisplay+"'";

            // Create statement and execute query
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery(query);
            
            java.util.List<String> dateList=new java.util.ArrayList<>();
            while (resultSet.next()){
                Date orderDate = resultSet.getDate("date");
                System.out.println(orderDate.toString());
                dateList.add(orderDate.toString());
            }
            
            jComboArray=dateList.toArray(new String[dateList.size()]);
            jComboSelectdValue=jComboArray[0];
            System.out.println(jComboArray);
            System.out.println("hello world");
            System.out.println(jComboSelectdValue);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Shopping to see your products");
            
            
            
        }
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NewJFrame aboutUs=new NewJFrame();
        aboutUs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        OrderNowPage orderNow=new OrderNowPage();
        orderNow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void orderNowButtonHeader1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNowButtonHeader1ActionPerformed
        HomePage home=new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orderNowButtonHeader1ActionPerformed

    private void dropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownActionPerformed
        try{
            jComboSelectdValue = dropDown.getSelectedItem().toString();
        
            // Clear the dynamicPanel before adding new content
            dynamicPanel.removeAll();
            System.out.println(jComboSelectdValue);
            // Fetch data from the database based on the selected date
            fetchDataFromDatabase();

            // Repaint the dynamicPanel to reflect changes
            dynamicPanel.revalidate();
            dynamicPanel.repaint();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dropDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dropDown;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mainTotalPrice;
    private javax.swing.JButton orderNowButtonHeader1;
    private javax.swing.JPanel recursivePanel;
    private javax.swing.JSeparator recursiveSeperator;
    // End of variables declaration//GEN-END:variables
}
