/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package inf.admin;

import codes.DBConnect;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class FeedbackAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form FeedbackAdmin
     */
    Connection conn=null;
    PreparedStatement pst=null;
    Color[] colors={
        new Color(204,204,255),
        new Color(255,204,204),
        new Color(204,255,204),
        new Color(255,255,204),
        new Color(255,204,255),
        new Color(242,242,242)
    };
    public FeedbackAdmin() {
        
        conn=DBConnect.connect();
        
        initComponents();
        
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
        fetchDataFromDataBase();
        
        
    }
    
    public void fetchDataFromDataBase(){
        try{
            String query="SELECT name,email,message,date FROM feedbacks";
            Statement statement=conn.createStatement();
            ResultSet resultSet=statement.executeQuery(query);
            
            int colorNumber=0;
            int yPosition=20;
            while (resultSet.next()){

                if (colorNumber==5){
                    colorNumber=0;
                }

                String namev=resultSet.getString("name");
                String emailv=resultSet.getString("email");
                String messagev=resultSet.getString("message");
                Date datev=resultSet.getDate("date");

                customLabel(yPosition,namev,emailv,messagev,datev,colorNumber);

                colorNumber+=1;
                yPosition+=150;

            }
            dynamicPanel = new javax.swing.JPanel();
            dynamicPanel.setBackground(new java.awt.Color(255,255,255));
            jPanel1.add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, yPosition-120, 530, 130));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public JPanel customLabel(int yPosition,String namev,String emailv,String messagev,Date datev,int colorValue){

        dynamicPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        seperatorDynamic = new javax.swing.JSeparator();

        dynamicPanel.setBackground(colors[colorValue]);
        dynamicPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3,new java.awt.Color(0,204,204)));
        dynamicPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dynamicPanelMousePressed(evt);
            }
        });
        dynamicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText(namev);
        dynamicPanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 30));

        email.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setText(emailv);
        dynamicPanel.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 20));

        date.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        date.setForeground(new java.awt.Color(0,0,0));
        date.setText(datev.toString());
        dynamicPanel.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 60, -1));

        message.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        message.setText(messagev);
        dynamicPanel.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 480, 20));
        dynamicPanel.add(seperatorDynamic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 530, 10));

        jPanel1.add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, yPosition, 530, 130));

        return dynamicPanel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 650, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dynamicPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dynamicPanelMousePressed
            // TODO add your handling code here:
    }//GEN-LAST:event_dynamicPanelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JLabel email;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel name;
    private javax.swing.JSeparator seperatorDynamic;
    // End of variables declaration//GEN-END:variables
}
