/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package inf.admin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import codes.DBConnect;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Date;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class OrdersAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrdersAdmin
     */
    
    Connection conn=null;
    PreparedStatement pst=null;
    
    String nameComboSelectedValue="";
    String [] nameComboArray={};
    
    String dateComboSelectedValue="";
    String[] dateComboArray={};
    public OrdersAdmin() {
        conn=DBConnect.connect();
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
            
        nameDropDownSet();

        initComponents();

        
      
        fetchDataFromDatabase();
    }

    public void nameDropDownSet(){
        try{
            String query="Select distinct userName from userproducts";
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery(query);
            
            java.util.List<String> nameList=new java.util.ArrayList<>();
            while (resultSet.next()){
                String userName=resultSet.getString("userName");
                nameList.add(userName);
            }
            
            
            nameComboArray=nameList.toArray(new String[nameList.size()]);
            //nameComboSelectedValue=userNameCombo.getSelectedItem().toString();
            nameComboSelectedValue=nameComboArray[0];
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    public void fetchDataFromDatabase(){
        try{
            conn=DBConnect.connect();
            String query="select productName,quantity,price from userproducts where userName='"+nameComboSelectedValue+"'";
            Statement statement=conn.createStatement();
            ResultSet resultSet=statement.executeQuery(query);
            
            int yPosition=120;
            while (resultSet.next()){
                String productNamev=resultSet.getString("productName");
                int quantityv=resultSet.getInt("quantity");
                Double pricev=resultSet.getDouble("price");

                
                
                initComponentss(productNamev,quantityv,pricev,quantityv*pricev);
                yPosition+=150;
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public JPanel initComponentss(String productnamev,int qtyv,Double itempricev,Double totalpricev){
        dynamicPanel = new javax.swing.JPanel();
        jcomboPanel = new javax.swing.JPanel();
      
        userNameLabel = new javax.swing.JLabel();
       
        userNameCombo = new javax.swing.JComboBox<>();
        headerPanel = new javax.swing.JPanel();
        totalPriceLabel = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        qtyLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        dataPanelCustom = new javax.swing.JPanel();
        itemPriceRupee = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        totalPriceRupee = new javax.swing.JLabel();

        
        dynamicPanel.setBackground(new java.awt.Color(255, 255, 255));
        dynamicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcomboPanel.setBackground(new java.awt.Color(0, 0, 204));
        jcomboPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("User Name");
        jcomboPanel.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));



        userNameCombo.setBackground(new java.awt.Color(255, 153, 0));
        userNameCombo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(nameComboArray));
        userNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameComboActionPerformed(evt);
            }
        });
        jcomboPanel.add(userNameCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 150, 30));

        dynamicPanel.add(jcomboPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 550, 50));

        headerPanel.setBackground(new java.awt.Color(51, 0, 51));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalPriceLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        totalPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalPriceLabel.setText("Total Price");
        headerPanel.add(totalPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 90, 30));

        productNameLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        productNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        productNameLabel.setText("Product Name");
        headerPanel.add(productNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 20));

        qtyLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        qtyLabel.setForeground(new java.awt.Color(255, 255, 255));
        qtyLabel.setText("Qty");
        headerPanel.add(qtyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 30));

        priceLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("Item Price");
        headerPanel.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 90, 30));

        dynamicPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 550, 30));

        dataPanelCustom.setBackground(new java.awt.Color(204, 204, 255));
        dataPanelCustom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemPriceRupee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemPriceRupee.setText("Rs.");
        dataPanelCustom.add(itemPriceRupee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 20, 20));

        productName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productName.setText(productnamev);
        dataPanelCustom.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        qty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qty.setText(Integer.toString(qtyv));
        dataPanelCustom.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 30, 20));

        price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        price.setText(Double.toString(itempricev));
        dataPanelCustom.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 50, 20));

        totalPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalPrice.setText(Double.toString(totalpricev));
        dataPanelCustom.add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 60, 20));

        totalPriceRupee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalPriceRupee.setText("Rs.");
        dataPanelCustom.add(totalPriceRupee, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 20, 20));

        dynamicPanel.add(dataPanelCustom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 550, 40));
        
        return dynamicPanel;
   
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dynamicPanel = new javax.swing.JPanel();
        jcomboPanel = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        userNameCombo = new javax.swing.JComboBox<>();
        headerPanel = new javax.swing.JPanel();
        totalPriceLabel = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        qtyLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        dataPanelCustom = new javax.swing.JPanel();
        itemPriceRupee = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        totalPriceRupee = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dynamicPanel.setBackground(new java.awt.Color(255, 255, 255));
        dynamicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcomboPanel.setBackground(new java.awt.Color(0, 0, 204));
        jcomboPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("User Name");
        jcomboPanel.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        userNameCombo.setBackground(new java.awt.Color(255, 153, 0));
        userNameCombo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(nameComboArray));
        userNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameComboActionPerformed(evt);
            }
        });
        jcomboPanel.add(userNameCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 150, 30));

        dynamicPanel.add(jcomboPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 550, 50));

        headerPanel.setBackground(new java.awt.Color(51, 0, 51));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalPriceLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        totalPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalPriceLabel.setText("Total Price");
        headerPanel.add(totalPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 90, 30));

        productNameLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        productNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        productNameLabel.setText("Product Name");
        headerPanel.add(productNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 20));

        qtyLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        qtyLabel.setForeground(new java.awt.Color(255, 255, 255));
        qtyLabel.setText("Qty");
        headerPanel.add(qtyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 30));

        priceLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("Item Price");
        headerPanel.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 90, 30));

        dynamicPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 550, 30));

        dataPanelCustom.setBackground(new java.awt.Color(204, 204, 255));
        dataPanelCustom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemPriceRupee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemPriceRupee.setText("Rs.");
        dataPanelCustom.add(itemPriceRupee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 20, 20));

        productName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productName.setText("Submarine");
        dataPanelCustom.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        qty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qty.setText("10");
        dataPanelCustom.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 30, 20));

        price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        price.setText("110");
        dataPanelCustom.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 50, 20));

        totalPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalPrice.setText("1500");
        dataPanelCustom.add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 60, 20));

        totalPriceRupee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalPriceRupee.setText("Rs.");
        dataPanelCustom.add(totalPriceRupee, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 20, 20));

        dynamicPanel.add(dataPanelCustom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 550, 40));

        jScrollPane1.setViewportView(dynamicPanel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 640, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameComboActionPerformed
        nameComboSelectedValue=userNameCombo.getSelectedItem().toString();
        
    }//GEN-LAST:event_userNameComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataPanelCustom;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel itemPriceRupee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jcomboPanel;
    private javax.swing.JLabel price;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel qty;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JLabel totalPriceRupee;
    private javax.swing.JComboBox<String> userNameCombo;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
